/**
 * Pillar A (M2): dependency assessment agent for Renovate PRs.
 *
 * Deterministic classification first (dep-classification.ts), then:
 *  - safe:     short structured comment confirming classification (automerge is
 *              handled by Renovate + branch protection, not by this script).
 *  - risky:    validation checklist comment.
 *  - breaking: agent-researched impact comment — changelog digest from the PR body,
 *              affected call sites from a repo scan, suggested migration steps.
 *              HIGHLIGHT, NEVER AUTO-FIX (brief Pillar A).
 */

import { promises as fs } from "node:fs";
import path from "node:path";

import {
  classifyDependencyUpdate,
  extractChangelogExcerpt,
  findAffectedCallSites,
  type DepAssessmentClassification,
} from "./dep-classification.js";
import {
  appendStepSummary,
  GitHubClient,
  isNonFatalCommentPermissionError,
  requireEnv,
} from "./github.js";
import { bootstrapCursorSdkRuntime } from "./sdk-bootstrap.js";
import { resolvePromptRuntimeOptions, resolveRuntimeMode } from "./runtime-options.js";
import { promptWithModelFallback, resolveModelCandidates } from "./model-fallback.js";
import { writeRunSummary } from "./run-summary.js";

const COMMENT_MARKER = "<!-- cursor-dep-assessment -->";

const SCAN_ROOTS = ["apps", "packages", "scripts"];
const SCAN_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".mjs", ".go", ".yml", ".yaml", ".json"]);
const MAX_SCAN_FILES = 4000;

async function collectRepoFiles(repoRoot: string): Promise<Map<string, string>> {
  const files = new Map<string, string>();

  async function walk(dir: string): Promise<void> {
    if (files.size >= MAX_SCAN_FILES) return;
    let entries;
    try {
      entries = await fs.readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      if (files.size >= MAX_SCAN_FILES) return;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (["node_modules", ".next", "dist", "coverage", ".turbo"].includes(entry.name)) {
          continue;
        }
        await walk(full);
      } else if (entry.isFile() && SCAN_EXTENSIONS.has(path.extname(entry.name))) {
        try {
          files.set(path.relative(repoRoot, full), await fs.readFile(full, "utf8"));
        } catch {
          // unreadable file: skip
        }
      }
    }
  }

  for (const root of SCAN_ROOTS) {
    await walk(path.join(repoRoot, root));
  }
  return files;
}

function extractAgentText(result: unknown): string {
  if (!result || typeof result !== "object") return String(result);
  const candidate = result as Record<string, unknown>;
  if (typeof candidate.result === "string") return candidate.result;
  if (typeof candidate.output === "string") return candidate.output;
  return JSON.stringify(result, null, 2);
}

function buildSafeComment(classification: DepAssessmentClassification): string {
  return `${COMMENT_MARKER}
## Dependency Assessment — ${classification.classification.toUpperCase()}

| Field | Value |
|---|---|
| Update type | ${classification.updateType} |
| Ecosystems | ${classification.ecosystems.join(", ") || "unknown"} |
| Dependencies | ${classification.dependencies.map((d) => `${d.name} ${d.fromVersion ?? "?"} → ${d.toVersion ?? "?"}`).join("<br>") || "could not parse"} |
| Reasons | ${classification.reasons.join("; ")} |

${
  classification.classification === "safe"
    ? "Eligible for automerge once required checks (CI + Sonar) are green — Renovate + branch protection handle the merge; no agent action required."
    : "Validation checklist: run the affected packages' tests, check the changelog for behavioral notes, and merge manually once CI + Sonar are green."
}

_Generated by the dependency assessment agent (Pillar A, M2)._`;
}

async function buildBreakingComment(
  classification: DepAssessmentClassification,
  prBody: string | null,
  agent: {
    prompt: (
      prompt: string,
      options: Record<string, unknown>
    ) => Promise<unknown>;
  },
  runtimeOptions: Record<string, unknown>
): Promise<string> {
  const repoRoot = process.cwd().includes("packages/cursor-agents")
    ? path.resolve(process.cwd(), "../..")
    : process.cwd();
  const repoFiles = await collectRepoFiles(repoRoot);

  const callSitesByDep = classification.dependencies.map((dep) => ({
    dep,
    callSites: findAffectedCallSites(dep.name, repoFiles),
  }));

  const changelog = extractChangelogExcerpt(prBody);
  const callSiteSummary = callSitesByDep
    .map(
      ({ dep, callSites }) =>
        `${dep.name}: ${callSites.length === 0 ? "no direct references found" : callSites.slice(0, 30).join(", ")}`
    )
    .join("\n");

  const prompt = `
You are assessing a BREAKING dependency update PR. Do not propose committing fixes — highlight impact only.

Dependencies updated:
${classification.dependencies.map((d) => `- ${d.name}: ${d.fromVersion ?? "?"} -> ${d.toVersion ?? "?"}`).join("\n")}

Changelog / release notes excerpt from the PR body:
${changelog}

Affected call sites found by repository scan:
${callSiteSummary || "none found"}

Produce markdown with exactly these sections:
1) Impact summary (2-4 sentences)
2) Breaking changes list (bullet each relevant breaking change from the changelog; ignore irrelevant ones)
3) Affected call sites (map breaking changes to the files above; say "none" where no usage exists)
4) Proposed migration steps (ordered, smallest-safe-change first)
5) Recommendation (merge after migration / defer / safe despite major)
`;

  const { result } = await promptWithModelFallback(
    resolveModelCandidates(process.env.CURSOR_TRIAGE_MODEL),
    (modelId) =>
      agent.prompt(prompt, {
        apiKey: requireEnv("CURSOR_API_KEY"),
        model: { id: modelId },
        ...runtimeOptions,
      })
  );

  const status = (result as { status?: string }).status;
  if (status && status !== "finished") {
    throw new Error(`Dependency assessment agent returned non-success status: ${status}`);
  }

  return `${COMMENT_MARKER}
## Dependency Assessment — BREAKING

| Field | Value |
|---|---|
| Update type | ${classification.updateType} |
| Ecosystems | ${classification.ecosystems.join(", ") || "unknown"} |
| Reasons | ${classification.reasons.join("; ")} |

${extractAgentText(result)}

> Policy: breaking updates are **never auto-applied**. This comment is research, not a fix (brief Pillar A).

_Generated by the dependency assessment agent (Pillar A, M2)._`;
}

async function main(): Promise<void> {
  bootstrapCursorSdkRuntime();
  const { Agent, CursorAgentError } = await import("@cursor/sdk");

  const githubToken = requireEnv("GITHUB_TOKEN");
  const repository = requireEnv("GITHUB_REPOSITORY");
  const prNumber = Number(requireEnv("PR_NUMBER"));
  const github = new GitHubClient({ token: githubToken, repository });
  const runtimeMode = resolveRuntimeMode();
  const runtimeOptions = resolvePromptRuntimeOptions();

  const startedAt = new Date();
  try {
    const pullRequest = await github.getPullRequest(prNumber);
    const files = await github.getPullRequestFiles(prNumber);
    const labels = (await github.listIssueLabels(prNumber)).map((label) => label.name);

    const classification = classifyDependencyUpdate({
      title: pullRequest.title,
      body: pullRequest.body,
      labels,
      changedFiles: files.map((file) => file.filename),
    });

    const comment =
      classification.classification === "breaking"
        ? await buildBreakingComment(classification, pullRequest.body, Agent, runtimeOptions)
        : buildSafeComment(classification);

    let posted = true;
    try {
      await github.upsertIssueComment(prNumber, COMMENT_MARKER, comment);
    } catch (error) {
      if (!isNonFatalCommentPermissionError(error)) throw error;
      posted = false;
    }

    appendStepSummary(comment);
    writeRunSummary({
      job: "dep-assessment",
      trigger: `pr#${prNumber}`,
      runtime: runtimeMode,
      startedAt,
      outcome: "success",
      details: {
        classification: classification.classification,
        updateType: classification.updateType,
        dependencies: classification.dependencies.map((d) => d.name),
        commentPosted: posted,
      },
    });
    console.log(
      `Dependency assessment completed: ${classification.classification} (runtime=${runtimeMode})`
    );
  } catch (error) {
    writeRunSummary({
      job: "dep-assessment",
      trigger: `pr#${prNumber}`,
      runtime: runtimeMode,
      startedAt,
      outcome: "failure",
      details: { error: String(error) },
    });
    if (error instanceof CursorAgentError) {
      throw new Error(
        `Cursor agent startup failed (retryable=${error.isRetryable}): ${error.message}`
      );
    }
    throw error;
  }
}

void main();
