import { Agent, CursorAgentError } from "@cursor/sdk";
import {
  appendStepSummary,
  GitHubClient,
  isNonFatalCommentPermissionError,
  requireEnv,
  truncate,
  type PullRequestFile,
} from "./github.js";
import { bootstrapCursorSdkRuntime } from "./sdk-bootstrap.js";

const COMMENT_MARKER = "<!-- cursor-pr-review -->";

function buildDiffContext(files: PullRequestFile[]): string {
  const changedFiles = files.slice(0, 30).map((file) => {
    const patch = file.patch ? truncate(file.patch, 3000) : "[no textual patch available]";
    return [
      `File: ${file.filename}`,
      `Status: ${file.status}, +${file.additions} -${file.deletions}`,
      "Patch:",
      patch,
    ].join("\n");
  });

  return changedFiles.join("\n\n---\n\n");
}

function extractAgentText(result: unknown): string {
  if (!result || typeof result !== "object") {
    return String(result);
  }

  const candidate = result as Record<string, unknown>;
  if (typeof candidate.result === "string") {
    return candidate.result;
  }
  if (typeof candidate.output === "string") {
    return candidate.output;
  }

  return JSON.stringify(result, null, 2);
}

async function main(): Promise<void> {
  bootstrapCursorSdkRuntime();

  const apiKey = requireEnv("CURSOR_API_KEY");
  const githubToken = requireEnv("GITHUB_TOKEN");
  const repository = requireEnv("GITHUB_REPOSITORY");
  const prNumber = Number(requireEnv("PR_NUMBER"));

  const github = new GitHubClient({ token: githubToken, repository });
  const pullRequest = await github.getPullRequest(prNumber);
  const files = await github.getPullRequestFiles(prNumber);
  const diffContext = buildDiffContext(files);

  const prompt = `
You are reviewing pull request #${pullRequest.number} in ${repository}.

Title: ${pullRequest.title}
Author: ${pullRequest.user.login}
Base: ${pullRequest.base.ref}
Head: ${pullRequest.head.ref}

PR Body:
${pullRequest.body ?? "(empty)"}

Changed files count: ${files.length}
Changed files and partial patches:
${diffContext}

Return a concise markdown review with these sections:
1) High-risk findings (bugs, regressions, security risks)
2) Medium-risk findings
3) Missing tests or validation risks
4) Suggested next actions

If no major issues are found, state that clearly and still include test/verification gaps.
`;

  try {
    const result = await Agent.prompt(prompt, {
      apiKey,
      model: { id: "composer-2" },
      local: { cwd: process.cwd() },
    });

    const status = (result as { status?: string }).status;
    if (status && status !== "finished") {
      throw new Error(`Cursor PR review run finished with non-success status: ${status}`);
    }

    const review = extractAgentText(result);
    const body = `${COMMENT_MARKER}
## Cursor PR Review

${review}

_Generated by Cursor SDK workflow (cursor-pr-review.yml)._`;

    try {
      await github.upsertIssueComment(prNumber, COMMENT_MARKER, body);
    } catch (error) {
      if (!isNonFatalCommentPermissionError(error)) {
        throw error;
      }

      const fallback = `${body}

> Note: PR comment was not posted due to token permissions (403 Resource not accessible by integration).`;
      appendStepSummary(fallback);
      return;
    }

    appendStepSummary(body);
  } catch (error) {
    if (error instanceof CursorAgentError) {
      throw new Error(
        `Cursor agent startup failed (retryable=${error.isRetryable}): ${error.message}`
      );
    }
    throw error;
  }
}

void main();
