import { Agent, CursorAgentError } from "@cursor/sdk";
import {
  appendStepSummary,
  GitHubClient,
  requireEnv,
  truncate,
  type CodeScanningAlert,
  type DependabotAlert,
  type PullRequestFile,
} from "./github.js";

const COMMENT_MARKER = "<!-- cursor-security-triage -->";

function buildDependabotPatchContext(files: PullRequestFile[]): string {
  return files
    .slice(0, 20)
    .map((file) => {
      const patch = file.patch ? truncate(file.patch, 2500) : "[no textual patch available]";
      return [
        `File: ${file.filename}`,
        `Status: ${file.status}, +${file.additions} -${file.deletions}`,
        "Patch:",
        patch,
      ].join("\n");
    })
    .join("\n\n---\n\n");
}

function summarizeCodeScanningAlerts(alerts: CodeScanningAlert[]): string {
  if (alerts.length === 0) {
    return "No open code scanning alerts.";
  }

  return alerts
    .slice(0, 30)
    .map((alert) => {
      const path = alert.most_recent_instance?.location?.path ?? "unknown";
      const line = alert.most_recent_instance?.location?.start_line ?? "?";
      return `- #${alert.number} | rule=${alert.rule?.id ?? "unknown"} | severity=${alert.rule?.severity ?? "unknown"} | ${path}:${line}`;
    })
    .join("\n");
}

function summarizeDependabotAlerts(alerts: DependabotAlert[]): string {
  if (alerts.length === 0) {
    return "No open dependabot alerts or token lacks access.";
  }

  return alerts
    .slice(0, 30)
    .map((alert) => {
      const pkg = alert.dependency?.package?.name ?? "unknown-package";
      const ecosystem = alert.dependency?.package?.ecosystem ?? "unknown-ecosystem";
      const severity = alert.security_advisory?.severity ?? "unknown";
      const cve = alert.security_advisory?.cve_id ?? "no-cve";
      return `- #${alert.number} | ${ecosystem}:${pkg} | severity=${severity} | ${cve}`;
    })
    .join("\n");
}

function extractAgentText(result: unknown): string {
  if (!result || typeof result !== "object") {
    return String(result);
  }

  const candidate = result as Record<string, unknown>;
  if (typeof candidate.result === "string") {
    return candidate.result;
  }
  if (typeof candidate.output === "string") {
    return candidate.output;
  }

  return JSON.stringify(result, null, 2);
}

async function runDependabotPrTriage(github: GitHubClient, repository: string): Promise<string> {
  const prNumber = Number(requireEnv("PR_NUMBER"));
  const pullRequest = await github.getPullRequest(prNumber);
  const files = await github.getPullRequestFiles(prNumber);
  const patchContext = buildDependabotPatchContext(files);

  const prompt = `
You are triaging a Dependabot pull request.

Repository: ${repository}
PR: #${pullRequest.number} ${pullRequest.title}
Base: ${pullRequest.base.ref}
Head: ${pullRequest.head.ref}

Changed files and partial patches:
${patchContext}

Produce markdown with:
1) Security impact and urgency
2) Breaking-change risk
3) Validation checklist (tests/build/runtime checks)
4) Merge recommendation (safe now / safe with follow-up / hold)
`;

  const result = await Agent.prompt(prompt, {
    apiKey: requireEnv("CURSOR_API_KEY"),
    model: { id: "composer-2" },
    local: { cwd: process.cwd() },
  });

  const status = (result as { status?: string }).status;
  if (status && status !== "finished") {
    throw new Error(`Cursor dependabot triage returned non-success status: ${status}`);
  }

  const triage = extractAgentText(result);
  const commentBody = `${COMMENT_MARKER}
## Cursor Security Triage (Dependabot PR)

${triage}

_Generated by Cursor SDK workflow (cursor-security-triage.yml)._`;
  await github.upsertIssueComment(prNumber, COMMENT_MARKER, commentBody);

  return commentBody;
}

async function runAlertTriage(github: GitHubClient, repository: string): Promise<string> {
  const codeAlerts = await github.listCodeScanningAlerts();
  let dependabotSummary = "Dependabot alert query unavailable.";
  try {
    dependabotSummary = summarizeDependabotAlerts(await github.listDependabotAlerts());
  } catch {
    dependabotSummary = "Dependabot alert query unavailable with current token permissions.";
  }

  const prompt = `
You are triaging repository security findings.

Repository: ${repository}

Open code scanning alerts:
${summarizeCodeScanningAlerts(codeAlerts)}

Open dependabot alerts:
${dependabotSummary}

Produce markdown with:
1) Prioritized remediation queue (P1/P2/P3)
2) Immediate fixes this week
3) Safe deferrals and rationale
4) Suggested owners and verification checks
`;

  const result = await Agent.prompt(prompt, {
    apiKey: requireEnv("CURSOR_API_KEY"),
    model: { id: "composer-2" },
    local: { cwd: process.cwd() },
  });

  const status = (result as { status?: string }).status;
  if (status && status !== "finished") {
    throw new Error(`Cursor security triage returned non-success status: ${status}`);
  }

  return `## Cursor Security Triage Report\n\n${extractAgentText(result)}`;
}

async function main(): Promise<void> {
  const githubToken = requireEnv("GITHUB_TOKEN");
  const repository = requireEnv("GITHUB_REPOSITORY");
  const github = new GitHubClient({ token: githubToken, repository });

  try {
    const output = process.env.PR_NUMBER
      ? await runDependabotPrTriage(github, repository)
      : await runAlertTriage(github, repository);

    appendStepSummary(output);
  } catch (error) {
    if (error instanceof CursorAgentError) {
      throw new Error(
        `Cursor agent startup failed (retryable=${error.isRetryable}): ${error.message}`
      );
    }
    throw error;
  }
}

void main();
